### ISSUE TITLE
Make plugin available on Deno, Bun, and browsers

### ISSUE THREAD

**Issue by micheleriva** [LyraSearch/plugin-data-persistence#2]
As for now, the plugin runs on Node.js, but it will need to run on any browser/runtime.
We should probably create different builds for different runtimes and environments to support a broader range of possibilities.

**Things to know**:
- `dpack` is a strategic dependency and it's supported in browsers, Node.js and Bun. We need to bundle it in some way to make the support available in Deno

**Comment by jkomyno** [comment]
Ciao Michele, have you considered using [`messagepack`](https://www.npmjs.com/package/@msgpack/msgpack) instead? It's a more widespread serialization format, and the linked library already ships with type definitions. It doesn't use any runtime deps, so most likely it's already compatible with Deno. What do you think?

**Comment by micheleriva** [comment]
Hey @jkomyno I guess we have to try it! I'd like to see how it compares with dpack

**Comment by castarco** [comment]
Because of plugin-astro, I was thinking about browser support, and my intuition tells me that this task might have to be split into smaller ones. Details I'm considering:

### Read-only stuff
- Loading files available via HTTP (so, mostly `fetch`)... even "remote" (in other domains) ones.
  - This would open a whole a can of worms, because of security, but it's still worth considering because it also makes possible to share DBs... for what? I don't know, there's crazy enough people out there to make something good out of it.
  - In any case we can constrain URLs to point to the same domain to begin with.

### More complex applications
- LocalStorage and its whole family of sibling APIs.

**Comment by micheleriva** [comment]
@castarco technically speaking, with the `0.0.1-alpha.1` you can bump a msgpack, dpack, or JSON index, store it on a S3 bucket or whatever object storage and import it from the browser. There are security concerns, but I guess they're out of scope for this plugin... maybe we should document some **do** and **don't** for the less experienced users.

`localStorage` is fully supported, and I agree that we should get rid of the `disk` word in the package name 🙂

**Comment by Zombobot1** [comment]
I tried to polyfill this plugin in `vite`, but failed due to #9. I find the current API a bit clunky, at least for my use case. Here is my implementation of serialization that is more convenient for uploading and caching for offline access.

```ts
import { Encoder, decodeAsync } from '@msgpack/msgpack'
import { PropertiesSchema, Lyra, save, create } from '@lyrasearch/lyra'

const encoder = new Encoder() // reuse to gain +20% performance https://github.com/msgpack/msgpack-javascript/blob/main/README.md#reusing-encoder-and-decoder-instances

export function persist<T extends PropertiesSchema>(db: Lyra<T>, name: string) {
  return new File([encoder.encode(save(db))], name, { type: 'application/octet-stream' })
}

export async function restore<T extends PropertiesSchema>(url: string): Promise<Lyra<T>> {
  const db = create({
    schema: {
      __placeholder: 'string',
    },
  })
  const blob = await fetch(url).then((res) => res.blob())
  const deserialized: any = await decodeAsync(blob.stream() as any) // streaming decode should be faster for large objects https://github.com/msgpack/msgpack-javascript/blob/main/README.md#decoding-a-blob

  db.index = deserialized.index
  db.defaultLanguage = deserialized.defaultLanguage
  db.docs = deserialized.docs
  db.nodes = deserialized.nodes
  db.schema = deserialized.schema
  db.frequencies = deserialized.frequencies
  db.tokenOccurrencies = deserialized.tokenOccurrencies
  return db as unknown as Lyra<T>
}

// Usage:
const file = persist(db, 'db.lyra')
const url = uploadFile(file)
cache.put(url, new Response(file)) // Web Cache API for offline use
const db = await restore<PropertiesSchema>(url)

```
