### ISSUE TITLE
Corrupted publish artifacts in 0.1.0?

### ISSUE THREAD

**Issue by n4bb12** [LyraSearch/plugin-data-persistence#23]
The files exported in `package.json` don't exist in the output.

See also https://www.npmjs.com/package/@lyrasearch/plugin-data-persistence/v/0.1.0?activeTab=explore

<img width="618" alt="2023-02-01 12_59_42-package json - combined-docs - Visual Studio Code" src="https://user-images.githubusercontent.com/6810177/216037252-8e42b9c3-2881-4c52-921a-ece2b221c4bb.png">

<img width="244" alt="2023-02-01 12_59_21-package json - combined-docs - Visual Studio Code" src="https://user-images.githubusercontent.com/6810177/216037249-1d69b4b2-c6c9-41fe-bfb1-f1a93203ccef.png">

**Comment by thiskevinwang** [comment]
I'm also noticing a VSCode-TS-Compiler error
- upgraded from `0.0.4` -> `0.1.0`

<img width="1002" alt="CleanShot 2023-02-02 at 09 40 37@2x" src="https://user-images.githubusercontent.com/26389321/216354933-48ed512f-25a7-44ef-82b1-730bc2ca87bc.png">

**Comment by mateonunez** [comment]
I think the problem here is in having used `pnpm` to run the `build` script, this did not start the `pre` and `post` hooks of the command, not generating the correct declarations. If `npm run build` is used instead of `pnpm` it appears that all files and declarations are correctly created.

What do you think, @ShogunPanda?

**Comment by ShogunPanda** [comment]
Yes, I found this problem in all the releases I made last week. They were all lacking the `.npmrc` file with pre and post scripts enabled.
I'm sorry I haven't noticed this before.
Tomorrow morning I'll release a fix versions of all of them.

**Comment by ShogunPanda** [comment]
Luckily only this package was affected.
This should have been fixed with https://github.com/LyraSearch/plugin-data-persistence/releases/tag/v0.1.1.
Can you please confirm?

**Comment by mateonunez** [comment]
> Can you please confirm?

Everything works fine for me. Thank you so much! 🚀
